-- Restaurant Platform - Initial Schema (PostgreSQL)
-- Rules:
-- 1) All primary and foreign keys use BIGINT.
-- 2) All table names use ts_ prefix.

BEGIN;

CREATE TABLE IF NOT EXISTS ts_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30),
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ts_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ts_roles_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS ts_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ts_user_roles_user FOREIGN KEY (user_id) REFERENCES ts_users(id),
    CONSTRAINT fk_ts_user_roles_role FOREIGN KEY (role_id) REFERENCES ts_roles(id),
    CONSTRAINT uq_ts_user_roles_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS ts_menu_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ts_menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    image_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ts_menu_items_category FOREIGN KEY (category_id) REFERENCES ts_menu_categories(id)
);

CREATE TABLE IF NOT EXISTS ts_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_code VARCHAR(30) NOT NULL UNIQUE,
    table_name VARCHAR(80) NOT NULL,
    seat_count INTEGER NOT NULL DEFAULT 2,
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ts_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    table_id BIGINT,
    order_code VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    subtotal_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ts_orders_user FOREIGN KEY (user_id) REFERENCES ts_users(id),
    CONSTRAINT fk_ts_orders_table FOREIGN KEY (table_id) REFERENCES ts_tables(id),
    CONSTRAINT uq_ts_orders_order_code UNIQUE (order_code),
    CONSTRAINT chk_ts_orders_status CHECK (status IN ('NEW', 'CONFIRMED', 'SERVED', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS ts_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    line_total NUMERIC(12,2) NOT NULL,
    note VARCHAR(255),
    CONSTRAINT fk_ts_order_items_order FOREIGN KEY (order_id) REFERENCES ts_orders(id),
    CONSTRAINT fk_ts_order_items_menu_item FOREIGN KEY (menu_item_id) REFERENCES ts_menu_items(id),
    CONSTRAINT chk_ts_order_items_quantity CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS ts_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PAID',
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ts_payments_order FOREIGN KEY (order_id) REFERENCES ts_orders(id)
);

CREATE TABLE IF NOT EXISTS ts_inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    quantity_on_hand NUMERIC(14,3) NOT NULL DEFAULT 0,
    min_threshold NUMERIC(14,3) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ts_inventory_items_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS ts_inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    txn_type VARCHAR(30) NOT NULL,
    quantity NUMERIC(14,3) NOT NULL,
    unit_cost NUMERIC(12,2),
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ts_inventory_txn_item FOREIGN KEY (inventory_item_id) REFERENCES ts_inventory_items(id)
);

CREATE TABLE IF NOT EXISTS ts_expense_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_code VARCHAR(50) NOT NULL UNIQUE,
    expense_name VARCHAR(150) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    occurred_on DATE NOT NULL,
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ts_menu_items_category_id
    ON ts_menu_items(category_id);

CREATE INDEX IF NOT EXISTS idx_ts_menu_items_is_active
    ON ts_menu_items(is_active);

CREATE INDEX IF NOT EXISTS idx_ts_orders_user_id_created_at
    ON ts_orders(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ts_orders_status_created_at
    ON ts_orders(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ts_order_items_order_id
    ON ts_order_items(order_id);

CREATE INDEX IF NOT EXISTS idx_ts_inventory_transactions_item_id_created_at
    ON ts_inventory_transactions(inventory_item_id, created_at DESC);

COMMIT;
